{"python_errors": " null\\n \"Error happened during upgrade: Traceback (most recent call last):\\n  File\\", "lab_server_machine_name": "bedrock-prod-nep-regsrvr-001", "ndm_version": "0.8.12", "test_duration": "0:38:42", "host_ip": "127.0.1.1"}